In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split


df = pd.read_csv('/Users/sadeedadnan/Documents/Spring 2022/ECS 171/project/dataframe_for_model.csv')
df

start  Bedrooms  Bathrooms  Total interior livable area  \
0          1         3          2                          872   
1          3         5          3                         2612   
2         10         4          2                         1579   
3         12         6          3                         3351   
4         18         3          2                         2100   
...      ...       ...        ...                          ...   
12486  47425         4          3                         2219   
12487  47427         4          5                         4680   
12488  47436         3          2                         1860   
12489  47437         3          3                         2125   
12490  47438         2          1                         1112   

       Elementary School Score  Middle School Score  High School Score  \
0                            3                    2                  2   
1                            9                    7                  8   
2                            7                    5                  6   
3                            8                    7                  7   
4                            6                    6                  8   
...                        ...                  ...                ...   
12486                        7                    7                  9   
12487                        7                    5                  7   
12488                        7                    3                  7   
12489                        7                    7                  8   
12490                        9                    8                  9   

       Tax assessed value  Annual tax amount  Listed Price           City  
0                  505000               6253        525000    Los Angeles  
1                 1775000              20787       1895000    Culver City  
2                   71347                904       1428000    Santa Clara  
3                 2080800              25099       2250000  San Francisco  
4                 1836000              21521       2390000      San Mateo  
...                   ...                ...           ...            ...  
12486              900775              12719       1224888       San Jose  
12487             2360150              25283       2569000     Villa Park  
12488              578000               7211       2295000    Los Angeles  
12489              484696               7627        499888      Elk Grove  
12490               49671               1089        748000   Los Alamitos  

[12491 rows x 11 columns]

In [7]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
df = pd.DataFrame(encoder.fit_transform(df), columns = df.columns)
df

start  Bedrooms  Bathrooms  Total interior livable area  \
0          0.0       3.0        2.0                        202.0   
1          1.0       5.0        3.0                       1875.0   
2          2.0       4.0        2.0                        889.0   
3          3.0       6.0        3.0                       2411.0   
4          4.0       3.0        2.0                       1402.0   
...        ...       ...        ...                          ...   
12486  12486.0       4.0        3.0                       1518.0   
12487  12487.0       4.0        5.0                       2845.0   
12488  12488.0       3.0        2.0                       1164.0   
12489  12489.0       3.0        3.0                       1426.0   
12490  12490.0       2.0        1.0                        427.0   

       Elementary School Score  Middle School Score  High School Score  \
0                          2.0                  1.0                1.0   
1                          8.0                  6.0                7.0   
2                          6.0                  4.0                5.0   
3                          7.0                  6.0                6.0   
4                          5.0                  5.0                7.0   
...                        ...                  ...                ...   
12486                      6.0                  6.0                8.0   
12487                      6.0                  4.0                6.0   
12488                      6.0                  2.0                6.0   
12489                      6.0                  6.0                7.0   
12490                      8.0                  7.0                8.0   

       Tax assessed value  Annual tax amount  Listed Price   City  
0                  5305.0             3495.0         524.0  191.0  
1                 10184.0             8116.0        1677.0   87.0  
2                   653.0              255.0        1419.0  320.0  
3                 10484.0             8544.0        1806.0  304.0  
4                 10254.0             8208.0        1846.0  313.0  
...                   ...                ...           ...    ...  
12486              7866.0             6359.0        1259.0  307.0  
12487             10654.0             8554.0        1891.0  374.0  
12488              5808.0             3945.0        1819.0  191.0  
12489              5146.0             4129.0         481.0  111.0  
12490               261.0              374.0         793.0  189.0  

[12491 rows x 11 columns]

In [9]:
x = df[['start','Bedrooms','Total interior livable area','Elementary School Score','Middle School Score','High School Score','Tax assessed value','Annual tax amount','City']]
y = df[['Listed Price']]

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [11]:
len(x_train)

9992

In [12]:
len(x_test)

2499

In [13]:
x_test

start  Bedrooms  Total interior livable area  \
8327    8327.0       3.0                        372.0   
4080    4080.0       3.0                        843.0   
6425    6425.0       4.0                       1800.0   
8417    8417.0       3.0                       1759.0   
5973    5973.0       4.0                       2054.0   
...        ...       ...                          ...   
10306  10306.0       3.0                       1089.0   
1578    1578.0       4.0                       2002.0   
11056  11056.0       4.0                       1188.0   
7344    7344.0       4.0                       1042.0   
8507    8507.0       2.0                        391.0   

       Elementary School Score  Middle School Score  High School Score  \
8327                       0.0                  2.0                4.0   
4080                       9.0                  8.0                5.0   
6425                       1.0                  4.0                3.0   
8417                       8.0                  5.0                5.0   
5973                       7.0                  7.0                7.0   
...                        ...                  ...                ...   
10306                      8.0                  6.0                7.0   
1578                       2.0                  3.0                4.0   
11056                      8.0                  4.0                6.0   
7344                       3.0                  1.0                5.0   
8507                       4.0                  3.0                6.0   

       Tax assessed value  Annual tax amount   City  
8327               2346.0             1097.0   95.0  
4080               6107.0             4565.0  300.0  
6425               4274.0             2761.0  191.0  
8417              10771.0             8732.0  355.0  
5973              10963.0             9109.0  292.0  
...                   ...                ...    ...  
10306              8807.0             6634.0   87.0  
1578              10525.0             8675.0  307.0  
11056              1444.0              508.0  143.0  
7344               2998.0             1883.0  378.0  
8507                436.0              917.0  304.0  

[2499 rows x 9 columns]

In [14]:
x_train

start  Bedrooms  Total interior livable area  \
10600  10600.0       3.0                        800.0   
11180  11180.0       3.0                       1813.0   
9010    9010.0       3.0                        737.0   
6964    6964.0       2.0                        810.0   
9758    9758.0       5.0                       2459.0   
...        ...       ...                          ...   
124      124.0       5.0                       2430.0   
6509    6509.0       4.0                       2122.0   
5923    5923.0       6.0                       2679.0   
9001    9001.0       2.0                        613.0   
12111  12111.0       3.0                        712.0   

       Elementary School Score  Middle School Score  High School Score  \
10600                      6.0                  4.0                6.0   
11180                      7.0                  7.0                7.0   
9010                       7.0                  2.0                5.0   
6964                       7.0                  6.0                6.0   
9758                       4.0                  3.0                6.0   
...                        ...                  ...                ...   
124                        7.0                  7.0                7.0   
6509                       7.0                  5.0                9.0   
5923                       6.0                  6.0                5.0   
9001                       8.0                  2.0                6.0   
12111                      7.0                  3.0                4.0   

       Tax assessed value  Annual tax amount   City  
10600              3136.0             1944.0  102.0  
11180              1988.0             1943.0  119.0  
9010               8661.0             6554.0  191.0  
6964               9355.0             7379.0  304.0  
9758               4888.0             2818.0  157.0  
...                   ...                ...    ...  
124                8299.0             6553.0  307.0  
6509              10961.0             9071.0  304.0  
5923               7029.0             5018.0  191.0  
9001               7165.0             5012.0  191.0  
12111               357.0             1107.0   27.0  

[9992 rows x 9 columns]

In [16]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
y_train

Listed Price
10600         693.0
11180        1325.0
9010         1391.0
6964         1541.0
9758          524.0
...             ...
124          1621.0
6509         2005.0
5923         1940.0
9001         1275.0
12111         915.0

[9992 rows x 1 columns]

In [17]:
model.fit(x_train,y_train)

/Users/sadeedadnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:1107: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/sadeedadnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [18]:
model.predict(x_test) #testing precision

array([257., 961.,   0., ..., 147., 961., 911.])

In [19]:
model.score(x_test,y_test)

0.009603841536614645

In [20]:
model.predict_proba(x_test)

array([[2.16570077e-03, 7.70904719e-05, 3.06063688e-08, ...,
        2.52060990e-07, 4.40171363e-11, 5.12563766e-14],
       [1.17880335e-03, 4.45906156e-09, 3.88777273e-05, ...,
        9.03049626e-05, 1.85811730e-06, 8.75359351e-08],
       [8.23057056e-03, 4.62464810e-07, 7.01250088e-07, ...,
        4.20105945e-05, 2.42655124e-08, 1.53830278e-10],
       ...,
       [3.32757729e-03, 4.68858132e-04, 4.18534836e-10, ...,
        5.96800563e-08, 2.37269578e-13, 2.87181826e-17],
       [4.68776586e-03, 1.21038342e-05, 1.91612470e-07, ...,
        4.23584775e-06, 1.38035287e-09, 3.87752593e-12],
       [3.27525170e-04, 1.01341153e-03, 2.13774823e-08, ...,
        5.04204901e-07, 3.93599475e-11, 3.77975872e-14]])

In [21]:
#Create the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [22]:
#Train the model and create predictions
model.fit(x_train, y_train)
predictions = model.predict(x_test)

/Users/sadeedadnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:1107: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/sadeedadnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [23]:
# Priniting Predictions
predictions

array([257., 961.,   0., ..., 147., 961., 911.])

In [24]:
#Calculate performance metrics
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00         2
        10.0       0.00      0.00      0.00         1
        20.0       0.00      0.00      0.00         1
        21.0       0.00      0.00      0.00         1
        29.0       0.00      0.00      0.00         1
        30.0       0.00      0.00      0.00         2
        35.0       0.00      0.00      0.00         1
        38.0       0.00      0.00      0.00         2
        41.0       0.00      0.00      0.00         2
        50.0       0.00      0.00      0.00         0
        51.0       0.00      0.00      0.00         2
        53.0       0.00      0.00      0.00         1
        56.0       0.00      0.00      0.00         1
        57.0       0.00      0.00      0.00         1
        61.0       0.00      0.00      0.00         1
        64.0       0.00      0.00      0.00         2
        65.0       0.00      0.00      0.00         1
        70.0       0.00    

/Users/sadeedadnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sadeedadnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sadeedadnan/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sa

In [25]:
#Generate a confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
